import Text from "~/components/atoms/Text";
import Link from "~/components/atoms/Link";

const Impressum: React.FC = () => {
  return (
    <section>
      <header className="flex flex-col items-center">
        <Text variant="title">IMPRESSUM</Text>
      </header>
      <br />
      <section>
        <Text variant="heading">ANJA BUETTNER</Text>
        <Text variant="paragraph">AM KAISERKAI 19</Text>
        <Text variant="paragraph">20457 HAMBURG</Text>
        <Text variant="paragraph">040 - 33473744</Text>
        <Text variant="paragraph">OFFICE@BOOTSHAUS-HAFENCITY.DE</Text>
      </section>
      <br />
      <section>
        <Text variant="heading">BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH</Text>
        <Text variant="paragraph">SITZ DER GESELLSCHAFT: HAMBURG</Text>
        <Text variant="paragraph">AMTSGERICHT HAMBURG</Text>
        <Text variant="paragraph">HRB 143684</Text>
        <Text variant="paragraph">USTLD: DE308809682</Text>
      </section>
      <br />
      <section>
        <Text variant="heading">DATENSCHUTZERKLÄRUNG</Text>
        <br />
        <Text variant="paragraph">
          WIR FREUEN UNS SEHR ÜBER IHR INTERESSE AN UNSEREM UNTERNEHMEN.
          DATENSCHUTZ HAT EINEN BESONDERS HOHEN STELLENWERT FÜR DIE
          GESCHÄFTSLEITUNG DER BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH. EINE
          NUTZUNG DER INTERNETSEITEN DER BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH
          IST GRUNDSÄTZLICH OHNE JEDE ANGABE PERSONENBEZOGENER DATEN MÖGLICH.
          SOFERN EINE BETROFFENE PERSON BESONDERE SERVICES UNSERES UNTERNEHMENS
          ÜBER UNSERE INTERNETSEITE IN ANSPRUCH NEHMEN MÖCHTE, KÖNNTE JEDOCH
          EINE VERARBEITUNG PERSONENBEZOGENER DATEN ERFORDERLICH WERDEN. IST DIE
          VERARBEITUNG PERSONENBEZOGENER DATEN ERFORDERLICH UND BESTEHT FÜR EINE
          SOLCHE VERARBEITUNG KEINE GESETZLICHE GRUNDLAGE, HOLEN WIR GENERELL
          EINE EINWILLIGUNG DER BETROFFENEN PERSON EIN.
        </Text>
        <br />
        <Text variant="paragraph">
          DIE VERARBEITUNG PERSONENBEZOGENER DATEN, BEISPIELSWEISE DES NAMENS,
          DER ANSCHRIFT, E-MAIL-ADRESSE ODER TELEFONNUMMER EINER BETROFFENEN
          PERSON, ERFOLGT STETS IM EINKLANG MIT DER DATENSCHUTZ-GRUNDVERORDNUNG
          UND IN ÜBEREINSTIMMUNG MIT DEN FÜR DIE BOOTSHAUS WH
          BETRIEBSGESELLSCHAFT MBH GELTENDEN LANDESSPEZIFISCHEN
          DATENSCHUTZBESTIMMUNGEN. MITTELS DIESER DATENSCHUTZERKLÄRUNG MÖCHTE
          UNSER UNTERNEHMEN DIE ÖFFENTLICHKEIT ÜBER ART, UMFANG UND ZWECK DER
          VON UNS ERHOBENEN, GENUTZTEN UND VERARBEITETEN PERSONENBEZOGENEN DATEN
          INFORMIEREN. FERNER WERDEN BETROFFENE PERSONEN MITTELS DIESER
          DATENSCHUTZERKLÄRUNG ÜBER DIE IHNEN ZUSTEHENDEN RECHTE AUFGEKLÄRT.
        </Text>
        <br />
        <Text variant="paragraph">
          DIE BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH HAT ALS FÜR DIE VERARBEITUNG
          VERANTWORTLICHER ZAHLREICHE TECHNISCHE UND ORGANISATORISCHE MASSNAHMEN
          UMGESETZT, UM EINEN MÖGLICHST LÜCKENLOSEN SCHUTZ DER ÜBER DIESE
          INTERNETSEITE VERARBEITETEN PERSONENBEZOGENEN DATEN SICHERZUSTELLEN.
          DENNOCH KÖNNEN INTERNETBASIERTE DATENÜBERTRAGUNGEN GRUNDSÄTZLICH
          SICHERHEITSLÜCKEN AUFWEISEN, SODASS EIN ABSOLUTER SCHUTZ NICHT
          GEWÄHRLEISTET WERDEN KANN. AUS DIESEM GRUND STEHT ES JEDER BETROFFENEN
          PERSON FREI, PERSONENBEZOGENE DATEN AUCH AUF ALTERNATIVEN WEGEN,
          BEISPIELSWEISE TELEFONISCH, AN UNS ZU ÜBERMITTELN
        </Text>
      </section>
      <br />
      <section>
        <Text variant="heading">1. BEGRIFFSBESTIMMUNGEN</Text>
        <br />
        <Text variant="paragraph">
          DIE DATENSCHUTZERKLÄRUNG DER BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH
          BERUHT AUF DEN BEGRIFFLICHKEITEN, DIE DURCH DEN EUROPÄISCHEN
          RICHTLINIEN- UND VERORDNUNGSGEBER BEIM ERLASS DER
          DATENSCHUTZ-GRUNDVERORDNUNG (DS-GVO) VERWENDET WURDEN. UNSERE
          DATENSCHUTZERKLÄRUNG SOLL SOWOHL FÜR DIE ÖFFENTLICHKEIT ALS AUCH FÜR
          UNSERE KUNDEN UND GESCHÄFTSPARTNER EINFACH LESBAR UND VERSTÄNDLICH
          SEIN. UM DIES ZU GEWÄHRLEISTEN, MÖCHTEN WIR VORAB DIE VERWENDETEN
          BEGRIFFLICHKEITEN ERLÄUTERN.
        </Text>
        <br />
        <Text variant="paragraph">
          WIR VERWENDEN IN DIESER DATENSCHUTZERKLÄRUNG UNTER ANDEREM DIE
          FOLGENDEN BEGRIFFE:
        </Text>
        <br />
        <section className="ml-2">
          <Text variant="heading">A) PERSONENBEZOGENE DATEN</Text>
          <br />
          <Text variant="paragraph">
            PERSONENBEZOGENE DATEN SIND ALLE INFORMATIONEN, DIE SICH AUF EINE
            IDENTIFIZIERTE ODER IDENTIFIZIERBARE NATÜRLICHE PERSON (IM FOLGENDEN
            „BETROFFENE PERSON“) BEZIEHEN. ALS IDENTIFIZIERBAR WIRD EINE
            NATÜRLICHE PERSON ANGESEHEN, DIE DIREKT ODER INDIREKT, INSBESONDERE
            MITTELS ZUORDNUNG ZU EINER KENNUNG WIE EINEM NAMEN, ZU EINER
            KENNNUMMER, ZU STANDORTDATEN, ZU EINER ONLINE-KENNUNG ODER ZU EINEM
            ODER MEHREREN BESONDEREN MERKMALEN, DIE AUSDRUCK DER PHYSISCHEN,
            PHYSIOLOGISCHEN, GENETISCHEN, PSYCHISCHEN, WIRTSCHAFTLICHEN,
            KULTURELLEN ODER SOZIALEN IDENTITÄT DIESER NATÜRLICHEN PERSON SIND,
            IDENTIFIZIERT WERDEN KANN.
          </Text>
          <br />
          <Text variant="heading">B) BETROFFENE PERSON</Text>
          <br />
          <Text variant="paragraph">
            BETROFFENE PERSON IST JEDE IDENTIFIZIERTE ODER IDENTIFIZIERBARE
            NATÜRLICHE PERSON, DEREN PERSONENBEZOGENE DATEN VON DEM FÜR DIE
            VERARBEITUNG VERANTWORTLICHEN VERARBEITET WERDEN.
          </Text>
          <br />
          <Text variant="heading">C) VERARBEITUNG</Text>
          <br />
          <Text variant="paragraph">
            VERARBEITUNG IST JEDER MIT ODER OHNE HILFE AUTOMATISIERTER VERFAHREN
            AUSGEFÜHRTE VORGANG ODER JEDE SOLCHE VORGANGSREIHE IM ZUSAMMENHANG
            MIT PERSONENBEZOGENEN DATEN WIE DAS ERHEBEN, DAS ERFASSEN, DIE
            ORGANISATION, DAS ORDNEN, DIE SPEICHERUNG, DIE ANPASSUNG ODER
            VERÄNDERUNG, DAS AUSLESEN, DAS ABFRAGEN, DIE VERWENDUNG, DIE
            OFFENLEGUNG DURCH ÜBERMITTLUNG, VERBREITUNG ODER EINE ANDERE FORM
            DER BEREITSTELLUNG, DEN ABGLEICH ODER DIE VERKNÜPFUNG, DIE
            EINSCHRÄNKUNG, DAS LÖSCHEN ODER DIE VERNICHTUNG.
          </Text>
          <br />
          <Text variant="heading">D) EINSCHRÄNKUNG DER VERARBEITUNG</Text>
          <br />
          <Text variant="paragraph">
            EINSCHRÄNKUNG DER VERARBEITUNG IST DIE MARKIERUNG GESPEICHERTER
            PERSONENBEZOGENER DATEN MIT DEM ZIEL, IHRE KÜNFTIGE VERARBEITUNG
            EINZUSCHRÄNKEN.
          </Text>
          <br />
          <Text variant="heading">E) PROFILING</Text>
          <br />
          <Text variant="paragraph">
            PROFILING IST JEDE ART DER AUTOMATISIERTEN VERARBEITUNG
            PERSONENBEZOGENER DATEN, DIE DARIN BESTEHT, DASS DIESE
            PERSONENBEZOGENEN DATEN VERWENDET WERDEN, UM BESTIMMTE PERSÖNLICHE
            ASPEKTE, DIE SICH AUF EINE NATÜRLICHE PERSON BEZIEHEN, ZU BEWERTEN,
            INSBESONDERE, UM ASPEKTE BEZÜGLICH ARBEITSLEISTUNG, WIRTSCHAFTLICHER
            LAGE, GESUNDHEIT, PERSÖNLICHER VORLIEBEN, INTERESSEN,
            ZUVERLÄSSIGKEIT, VERHALTEN, AUFENTHALTSORT ODER ORTSWECHSEL DIESER
            NATÜRLICHEN PERSON ZU ANALYSIEREN ODER VORHERZUSAGEN.
          </Text>
          <br />
          <Text variant="heading">F) PSEUDONYMISIERUNG</Text>
          <br />
          <Text variant="paragraph">
            PSEUDONYMISIERUNG IST DIE VERARBEITUNG PERSONENBEZOGENER DATEN IN
            EINER WEISE, AUF WELCHE DIE PERSONENBEZOGENEN DATEN OHNE
            HINZUZIEHUNG ZUSÄTZLICHER INFORMATIONEN NICHT MEHR EINER
            SPEZIFISCHEN BETROFFENEN PERSON ZUGEORDNET WERDEN KÖNNEN, SOFERN
            DIESE ZUSÄTZLICHEN INFORMATIONEN GESONDERT AUFBEWAHRT WERDEN UND
            TECHNISCHEN UND ORGANISATORISCHEN MASSNAHMEN UNTERLIEGEN, DIE
            GEWÄHRLEISTEN, DASS DIE PERSONENBEZOGENEN DATEN NICHT EINER
            IDENTIFIZIERTEN ODER IDENTIFIZIERBAREN NATÜRLICHEN PERSON ZUGEWIESEN
            WERDEN
          </Text>
          <br />
          <Text variant="heading">
            G) VERANTWORTLICHER ODER FÜR DIE VERARBEITUNG VERANTWORTLICHER
          </Text>
          <br />
          <Text variant="paragraph">
            VERANTWORTLICHER ODER FÜR DIE VERARBEITUNG VERANTWORTLICHER IST DIE
            NATÜRLICHE ODER JURISTISCHE PERSON, BEHÖRDE, EINRICHTUNG ODER ANDERE
            STELLE, DIE ALLEIN ODER GEMEINSAM MIT ANDEREN ÜBER DIE ZWECKE UND
            MITTEL DER VERARBEITUNG VON PERSONENBEZOGENEN DATEN ENTSCHEIDET.
            SIND DIE ZWECKE UND MITTEL DIESER VERARBEITUNG DURCH DAS UNIONSRECHT
            ODER DAS RECHT DER MITGLIEDSTAATEN VORGEGEBEN, SO KANN DER
            VERANTWORTLICHE BEZIEHUNGSWEISE KÖNNEN DIE BESTIMMTEN KRITERIEN
            SEINER BENENNUNG NACH DEM UNIONSRECHT ODER DEM RECHT DER
            MITGLIEDSTAATEN VORGESEHEN WERDEN.
          </Text>
          <br />
          <Text variant="heading">H) AUFTRAGSVERARBEITER</Text>
          <br />
          <Text variant="paragraph">
            AUFTRAGSVERARBEITER IST EINE NATÜRLICHE ODER JURISTISCHE PERSON,
            BEHÖRDE, EINRICHTUNG ODER ANDERE STELLE, DIE PERSONENBEZOGENE DATEN
            IM AUFTRAG DES VERANTWORTLICHEN VERARBEITET.
          </Text>
          <br />
          <Text variant="heading">I) EMPFÄNGER</Text>
          <br />
          <Text variant="paragraph">
            EMPFÄNGER IST EINE NATÜRLICHE ODER JURISTISCHE PERSON, BEHÖRDE,
            EINRICHTUNG ODER ANDERE STELLE, DER PERSONENBEZOGENE DATEN
            OFFENGELEGT WERDEN, UNABHÄNGIG DAVON, OB ES SICH BEI IHR UM EINEN
            DRITTEN HANDELT ODER NICHT. BEHÖRDEN, DIE IM RAHMEN EINES BESTIMMTEN
            UNTERSUCHUNGSAUFTRAGS NACH DEM UNIONSRECHT ODER DEM RECHT DER
            MITGLIEDSTAATEN MÖGLICHERWEISE PERSONENBEZOGENE DATEN ERHALTEN,
            GELTEN JEDOCH NICHT ALS EMPFÄNGER.
          </Text>
          <br />
          <Text variant="heading">J) DRITTER</Text>
          <br />
          <Text variant="paragraph">
            DRITTER IST EINE NATÜRLICHE ODER JURISTISCHE PERSON, BEHÖRDE,
            EINRICHTUNG ODER ANDERE STELLE AUSSER DER BETROFFENEN PERSON, DEM
            VERANTWORTLICHEN, DEM AUFTRAGSVERARBEITER UND DEN PERSONEN, DIE
            UNTER DER UNMITTELBAREN VERANTWORTUNG DES VERANTWORTLICHEN ODER DES
            AUFTRAGSVERARBEITERS BEFUGT SIND, DIE PERSONENBEZOGENEN DATEN ZU
            VERARBEITEN
          </Text>
          <br />
          <Text variant="heading">K) EINWILLIGUNG</Text>
          <br />
          <Text variant="paragraph">
            EINWILLIGUNG IST JEDE VON DER BETROFFENEN PERSON FREIWILLIG FÜR DEN
            BESTIMMTEN FALL IN INFORMIERTER WEISE UND UNMISSVERSTÄNDLICH
            ABGEGEBENE WILLENSBEKUNDUNG IN FORM EINER ERKLÄRUNG ODER EINER
            SONSTIGEN EINDEUTIGEN BESTÄTIGENDEN HANDLUNG, MIT DER DIE BETROFFENE
            PERSON ZU VERSTEHEN GIBT, DASS SIE MIT DER VERARBEITUNG DER SIE
            BETREFFENDEN PERSONENBEZOGENEN DATEN EINVERSTANDEN IST.
          </Text>
        </section>
        <br />
        <section>
          <Text variant="heading">
            2. NAME UND ANSCHRIFT DES FÜR DIE VERARBEITUNG VERANTWORTLICHEN
          </Text>
          <br />
          <Text variant="paragraph">
            VERANTWORTLICHER IM SINNE DER DATENSCHUTZ-GRUNDVERORDNUNG, SONSTIGER
            IN DEN MITGLIEDSTAATEN DER EUROPÄISCHEN UNION GELTENDEN
            DATENSCHUTZGESETZE UND ANDERER BESTIMMUNGEN MIT
            DATENSCHUTZRECHTLICHEM CHARAKTER IST DIE:
          </Text>
          <br />
          <Text variant="paragraph">BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH</Text>
          <br />
          <Text variant="paragraph">20457 HAMBURG</Text>
          <br />
          <Text variant="paragraph">DEUTSCHLAND</Text>
          <br />
          <Text variant="paragraph">TEL.: 04033473744</Text>
          <br />
          <Text variant="paragraph">
            E-MAIL: RESERVIERUNG@BOOTSHAUS-HAFENCITY.DE
          </Text>
          <br />
          <Text variant="paragraph">WEBSITE: WWW.BOOTSHAUS-HAFENCITY.DE</Text>
        </section>
        <br />
        <section>
          <Text variant="heading">3. COOKIES</Text>
          <br />
          <Text variant="paragraph">
            DIE INTERNETSEITEN DER BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH
            VERWENDEN COOKIES. COOKIES SIND TEXTDATEIEN, WELCHE ÜBER EINEN
            INTERNETBROWSER AUF EINEM COMPUTERSYSTEM ABGELEGT UND GESPEICHERT
            WERDEN.
          </Text>
          <br />
          <Text variant="paragraph">
            ZAHLREICHE INTERNETSEITEN UND SERVER VERWENDEN COOKIES. VIELE
            COOKIES ENTHALTEN EINE SOGENANNTE COOKIE-ID. EINE COOKIE-ID IST EINE
            EINDEUTIGE KENNUNG DES COOKIES. SIE BESTEHT AUS EINER ZEICHENFOLGE,
            DURCH WELCHE INTERNETSEITEN UND SERVER DEM KONKRETEN INTERNETBROWSER
            ZUGEORDNET WERDEN KÖNNEN, IN DEM DAS COOKIE GESPEICHERT WURDE. DIES
            ERMÖGLICHT ES DEN BESUCHTEN INTERNETSEITEN UND SERVERN, DEN
            INDIVIDUELLEN BROWSER DER BETROFFENEN PERSON VON ANDEREN
            INTERNETBROWSERN, DIE ANDERE COOKIES ENTHALTEN, ZU UNTERSCHEIDEN.
            EIN BESTIMMTER INTERNETBROWSER KANN ÜBER DIE EINDEUTIGE COOKIE-ID
            WIEDERERKANNT UND IDENTIFIZIERT WERDEN.
          </Text>
          <br />
          <Text variant="paragraph">
            DURCH DEN EINSATZ VON COOKIES KANN DIE BOOTSHAUS WH
            BETRIEBSGESELLSCHAFT MBH DEN NUTZERN DIESER INTERNETSEITE
            NUTZERFREUNDLICHERE SERVICES BEREITSTELLEN, DIE OHNE DIE
            COOKIE-SETZUNG NICHT MÖGLICH WÄREN.
          </Text>
          <br />
          <Text variant="paragraph">
            MITTELS EINES COOKIES KÖNNEN DIE INFORMATIONEN UND ANGEBOTE AUF
            UNSERER INTERNETSEITE IM SINNE DES BENUTZERS OPTIMIERT WERDEN.
            COOKIES ERMÖGLICHEN UNS, WIE BEREITS ERWÄHNT, DIE BENUTZER UNSERER
            INTERNETSEITE WIEDERZUERKENNEN. ZWECK DIESER WIEDERERKENNUNG IST ES,
            DEN NUTZERN DIE VERWENDUNG UNSERER INTERNETSEITE ZU ERLEICHTERN. DER
            BENUTZER EINER INTERNETSEITE, DIE COOKIES VERWENDET, MUSS
            BEISPIELSWEISE NICHT BEI JEDEM BESUCH DER INTERNETSEITE ERNEUT SEINE
            ZUGANGSDATEN EINGEBEN, WEIL DIES VON DER INTERNETSEITE UND DEM AUF
            DEM COMPUTERSYSTEM DES BENUTZERS ABGELEGTEN COOKIE ÜBERNOMMEN WIRD.
            EIN WEITERES BEISPIEL IST DAS COOKIE EINES WARENKORBES IM
            ONLINE-SHOP. DER ONLINE-SHOP MERKT SICH DIE ARTIKEL, DIE EIN KUNDE
            IN DEN VIRTUELLEN WARENKORB GELEGT HAT, ÜBER EIN COOKIE.
          </Text>
          <br />
          <Text variant="paragraph">
            DIE BETROFFENE PERSON KANN DIE SETZUNG VON COOKIES DURCH UNSERE
            INTERNETSEITE JEDERZEIT MITTELS EINER ENTSPRECHENDEN EINSTELLUNG DES
            GENUTZTEN INTERNETBROWSERS VERHINDERN UND DAMIT DER SETZUNG VON
            COOKIES DAUERHAFT WIDERSPRECHEN. FERNER KÖNNEN BEREITS GESETZTE
            COOKIES JEDERZEIT ÜBER EINEN INTERNETBROWSER ODER ANDERE
            SOFTWAREPROGRAMME GELÖSCHT WERDEN. DIES IST IN ALLEN GÄNGIGEN
            INTERNETBROWSERN MÖGLICH. DEAKTIVIERT DIE BETROFFENE PERSON DIE
            SETZUNG VON COOKIES IN DEM GENUTZTEN INTERNETBROWSER, SIND UNTER
            UMSTÄNDEN NICHT ALLE FUNKTIONEN UNSERER INTERNETSEITE VOLLUMFÄNGLICH
            NUTZBAR.
          </Text>
        </section>
        <br />
        <section>
          <Text variant="heading">
            4. ERFASSUNG VON ALLGEMEINEN DATEN UND INFORMATIONEN
          </Text>
          <br />
          <Text variant="paragraph">
            DIE INTERNETSEITE DER BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH ERFASST
            MIT JEDEM AUFRUF DER INTERNETSEITE DURCH EINE BETROFFENE PERSON ODER
            EIN AUTOMATISIERTES SYSTEM EINE REIHE VON ALLGEMEINEN DATEN UND
            INFORMATIONEN. DIESE ALLGEMEINEN DATEN UND INFORMATIONEN WERDEN IN
            DEN LOGFILES DES SERVERS GESPEICHERT. ERFASST WERDEN KÖNNEN DIE (1)
            VERWENDETEN BROWSERTYPEN UND VERSIONEN, (2) DAS VOM ZUGREIFENDEN
            SYSTEM VERWENDETE BETRIEBSSYSTEM, (3) DIE INTERNETSEITE, VON WELCHER
            EIN ZUGREIFENDES SYSTEM AUF UNSERE INTERNETSEITE GELANGT (SOGENANNTE
            REFERRER), (4) DIE UNTERWEBSEITEN, WELCHE ÜBER EIN ZUGREIFENDES
            SYSTEM AUF UNSERER INTERNETSEITE ANGESTEUERT WERDEN, (5) DAS DATUM
            UND DIE UHRZEIT EINES ZUGRIFFS AUF DIE INTERNETSEITE, (6) EINE
            INTERNET-PROTOKOLL-ADRESSE (IP-ADRESSE), (7) DER
            INTERNET-SERVICE-PROVIDER DES ZUGREIFENDEN SYSTEMS UND (8) SONSTIGE
            ÄHNLICHE DATEN UND INFORMATIONEN, DIE DER GEFAHRENABWEHR IM FALLE
            VON ANGRIFFEN AUF UNSERE INFORMATIONSTECHNOLOGISCHEN SYSTEME DIENEN.
          </Text>
          <br />
          <Text variant="paragraph">
            BEI DER NUTZUNG DIESER ALLGEMEINEN DATEN UND INFORMATIONEN ZIEHT DIE
            BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH KEINE RÜCKSCHLÜSSE AUF DIE
            BETROFFENE PERSON. DIESE INFORMATIONEN WERDEN VIELMEHR BENÖTIGT, UM
            (1) DIE INHALTE UNSERER INTERNETSEITE KORREKT AUSZULIEFERN, (2) DIE
            INHALTE UNSERER INTERNETSEITE SOWIE DIE WERBUNG FÜR DIESE ZU
            OPTIMIEREN, (3) DIE DAUERHAFTE FUNKTIONSFÄHIGKEIT UNSERER
            INFORMATIONSTECHNOLOGISCHEN SYSTEME UND DER TECHNIK UNSERER
            INTERNETSEITE ZU GEWÄHRLEISTEN SOWIE (4) UM STRAFVERFOLGUNGSBEHÖRDEN
            IM FALLE EINES CYBERANGRIFFES DIE ZUR STRAFVERFOLGUNG NOTWENDIGEN
            INFORMATIONEN BEREITZUSTELLEN. DIESE ANONYM ERHOBENEN DATEN UND
            INFORMATIONEN WERDEN DURCH DIE BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH
            DAHER EINERSEITS STATISTISCH UND FERNER MIT DEM ZIEL AUSGEWERTET,
            DEN DATENSCHUTZ UND DIE DATENSICHERHEIT IN UNSEREM UNTERNEHMEN ZU
            ERHÖHEN, UM LETZTLICH EIN OPTIMALES SCHUTZNIVEAU FÜR DIE VON UNS
            VERARBEITETEN PERSONENBEZOGENEN DATEN SICHERZUSTELLEN. DIE ANONYMEN
            DATEN DER SERVER-LOGFILES WERDEN GETRENNT VON ALLEN DURCH EINE
            BETROFFENE PERSON ANGEGEBENEN PERSONENBEZOGENEN DATEN GESPEICHERT.
          </Text>
        </section>
        <br />
        <section>
          <Text variant="heading">
            5. ROUTINEMÄSSIGE LÖSCHUNG UND SPERRUNG VON PERSONENBEZOGENEN DATE
          </Text>
          <br />
          <Text variant="paragraph">
            DER FÜR DIE VERARBEITUNG VERANTWORTLICHE VERARBEITET UND SPEICHERT
            PERSONENBEZOGENE DATEN DER BETROFFENEN PERSON NUR FÜR DEN ZEITRAUM,
            DER ZUR ERREICHUNG DES SPEICHERUNGSZWECKS ERFORDERLICH IST ODER
            SOFERN DIES DURCH DEN EUROPÄISCHEN RICHTLINIEN- UND VERORDNUNGSGEBER
            ODER EINEN ANDEREN GESETZGEBER IN GESETZEN ODER VORSCHRIFTEN,
            WELCHEN DER FÜR DIE VERARBEITUNG VERANTWORTLICHE UNTERLIEGT,
            VORGESEHEN WURDE.
          </Text>
          <br />
          <Text variant="paragraph">
            ENTFÄLLT DER SPEICHERUNGSZWECK ODER LÄUFT EINE VOM EUROPÄISCHEN
            RICHTLINIEN- UND VERORDNUNGSGEBER ODER EINEM ANDEREN ZUSTÄNDIGEN
            GESETZGEBER VORGESCHRIEBENE SPEICHERFRIST AB, WERDEN DIE
            PERSONENBEZOGENEN DATEN ROUTINEMÄSSIG UND ENTSPRECHEND DEN
            GESETZLICHEN VORSCHRIFTEN GESPERRT ODER GELÖSCHT
          </Text>
        </section>
        <br />
        <section className="ml-2">
          <Text variant="heading">6. RECHTE DER BETROFFENEN PERSON</Text>
          <br />
          <section>
            <Text variant="heading">A) RECHT AUF BESTÄTIGUNG</Text>
            <br />
            <Text variant="paragraph">
              JEDE BETROFFENE PERSON HAT DAS VOM EUROPÄISCHEN RICHTLINIEN- UND
              VERORDNUNGSGEBER EINGERÄUMTE RECHT, VON DEM FÜR DIE VERARBEITUNG
              VERANTWORTLICHEN EINE BESTÄTIGUNG DARÜBER ZU VERLANGEN, OB SIE
              BETREFFENDE PERSONENBEZOGENE DATEN VERARBEITET WERDEN. MÖCHTE EINE
              BETROFFENE PERSON DIESES BESTÄTIGUNGSRECHT IN ANSPRUCH NEHMEN,
              KANN SIE SICH HIERZU JEDERZEIT AN EINEN MITARBEITER DES FÜR DIE
              VERARBEITUNG VERANTWORTLICHEN WENDEN.
            </Text>
            <br />
            <Text variant="heading">B) RECHT AUF AUSKUNFT</Text>
            <br />
            <Text variant="paragraph">
              JEDE VON DER VERARBEITUNG PERSONENBEZOGENER DATEN BETROFFENE
              PERSON HAT DAS VOM EUROPÄISCHEN RICHTLINIEN- UND VERORDNUNGSGEBER
              GEWÄHRTE RECHT, JEDERZEIT VON DEM FÜR DIE VERARBEITUNG
              VERANTWORTLICHEN UNENTGELTLICHE AUSKUNFT ÜBER DIE ZU SEINER PERSON
              GESPEICHERTEN PERSONENBEZOGENEN DATEN UND EINE KOPIE DIESER
              AUSKUNFT ZU ERHALTEN. FERNER HAT DER EUROPÄISCHE RICHTLINIEN- UND
              VERORDNUNGSGEBER DER BETROFFENEN PERSON AUSKUNFT ÜBER FOLGENDE
              INFORMATIONEN ZUGESTANDEN:
            </Text>
            <br />
            <section className="ml-2">
              <Text variant="paragraph">
                DIE VERARBEITUNGSZWECKE DIE KATEGORIEN PERSONENBEZOGENER DATEN,
                DIE VERARBEITET WERDEN DIE EMPFÄNGER ODER KATEGORIEN VON
                EMPFÄNGERN, GEGENÜBER DENEN DIE PERSONENBEZOGENEN DATEN
                OFFENGELEGT WORDEN SIND ODER NOCH OFFENGELEGT WERDEN,
                INSBESONDERE BEI EMPFÄNGERN IN DRITTLÄNDERN ODER BEI
                INTERNATIONALEN ORGANISATIONEN FALLS MÖGLICH DIE GEPLANTE DAUER,
                FÜR DIE DIE PERSONENBEZOGENEN DATEN GESPEICHERT WERDEN, ODER,
                FALLS DIES NICHT MÖGLICH IST, DIE KRITERIEN FÜR DIE FESTLEGUNG
                DIESER DAUER DAS BESTEHEN EINES RECHTS AUF BERICHTIGUNG ODER
                LÖSCHUNG DER SIE BETREFFENDEN PERSONENBEZOGENEN DATEN ODER AUF
                EINSCHRÄNKUNG DER VERARBEITUNG DURCH DEN VERANTWORTLICHEN ODER
                EINES WIDERSPRUCHSRECHTS GEGEN DIESE VERARBEITUNG DAS BESTEHEN
                EINES BESCHWERDERECHTS BEI EINER AUFSICHTSBEHÖRDE WENN DIE
                PERSONENBEZOGENEN DATEN NICHT BEI DER BETROFFENEN PERSON ERHOBEN
                WERDEN: ALLE VERFÜGBAREN INFORMATIONEN ÜBER DIE HERKUNFT DER
                DATEN DAS BESTEHEN EINER AUTOMATISIERTEN ENTSCHEIDUNGSFINDUNG
                EINSCHLIESSLICH PROFILING GEMÄSS ARTIKEL 22 ABS.1 UND 4 DS-GVO
                UND — ZUMINDEST IN DIESEN FÄLLEN — AUSSAGEKRÄFTIGE INFORMATIONEN
                ÜBER DIE INVOLVIERTE LOGIK SOWIE DIE TRAGWEITE UND DIE
                ANGESTREBTEN AUSWIRKUNGEN EINER DERARTIGEN VERARBEITUNG FÜR DIE
                BETROFFENE PERSON
              </Text>
            </section>
            <br />
            <Text variant="paragraph">
              FERNER STEHT DER BETROFFENEN PERSON EIN AUSKUNFTSRECHT DARÜBER ZU,
              OB PERSONENBEZOGENE DATEN AN EIN DRITTLAND ODER AN EINE
              INTERNATIONALE ORGANISATION ÜBERMITTELT WURDEN. SOFERN DIES DER
              FALL IST, SO STEHT DER BETROFFENEN PERSON IM ÜBRIGEN DAS RECHT ZU,
              AUSKUNFT ÜBER DIE GEEIGNETEN GARANTIEN IM ZUSAMMENHANG MIT DER
              ÜBERMITTLUNG ZU ERHALTEN.
            </Text>
            <br />
            <Text variant="paragraph">
              MÖCHTE EINE BETROFFENE PERSON DIESES AUSKUNFTSRECHT IN ANSPRUCH
              NEHMEN, KANN SIE SICH HIERZU JEDERZEIT AN EINEN MITARBEITER DES
              FÜR DIE VERARBEITUNG VERANTWORTLICHEN WENDEN.
            </Text>
            <br />
            <Text variant="heading">C) RECHT AUF BERICHTIGUNG</Text>
            <br />
            <Text variant="paragraph">
              JEDE VON DER VERARBEITUNG PERSONENBEZOGENER DATEN BETROFFENE
              PERSON HAT DAS VOM EUROPÄISCHEN RICHTLINIEN- UND VERORDNUNGSGEBER
              GEWÄHRTE RECHT, DIE UNVERZÜGLICHE BERICHTIGUNG SIE BETREFFENDER
              UNRICHTIGER PERSONENBEZOGENER DATEN ZU VERLANGEN. FERNER STEHT DER
              BETROFFENEN PERSON DAS RECHT ZU, UNTER BERÜCKSICHTIGUNG DER ZWECKE
              DER VERARBEITUNG, DIE VERVOLLSTÄNDIGUNG UNVOLLSTÄNDIGER
              PERSONENBEZOGENER DATEN — AUCH MITTELS EINER ERGÄNZENDEN ERKLÄRUNG
              — ZU VERLANGEN.
            </Text>
            <br />
            <Text variant="paragraph">
              MÖCHTE EINE BETROFFENE PERSON DIESES BERICHTIGUNGSRECHT IN
              ANSPRUCH NEHMEN, KANN SIE SICH HIERZU JEDERZEIT AN EINEN
              MITARBEITER DES FÜR DIE VERARBEITUNG VERANTWORTLICHEN WENDEN.
            </Text>
            <br />
            <Text variant="heading">
              D) RECHT AUF LÖSCHUNG (RECHT AUF VERGESSEN WERDEN)
            </Text>
            <br />
            <Text variant="paragraph">
              JEDE VON DER VERARBEITUNG PERSONENBEZOGENER DATEN BETROFFENE
              PERSON HAT DAS VOM EUROPÄISCHEN RICHTLINIEN- UND VERORDNUNGSGEBER
              GEWÄHRTE RECHT, VON DEM VERANTWORTLICHEN ZU VERLANGEN, DASS DIE
              SIE BETREFFENDEN PERSONENBEZOGENEN DATEN UNVERZÜGLICH GELÖSCHT
              WERDEN, SOFERN EINER DER FOLGENDEN GRÜNDE ZUTRIFFT UND SOWEIT DIE
              VERARBEITUNG NICHT ERFORDERLICH IST:
            </Text>
            <br />
            <section className="ml-2">
              <Text variant="paragraph">
                DIE PERSONENBEZOGENEN DATEN WURDEN FÜR SOLCHE ZWECKE ERHOBEN
                ODER AUF SONSTIGE WEISE VERARBEITET, FÜR WELCHE SIE NICHT MEHR
                NOTWENDIG SIND. DIE BETROFFENE PERSON WIDERRUFT IHRE
                EINWILLIGUNG, AUF DIE SICH DIE VERARBEITUNG GEMÄSS ART. 6 ABS. 1
                BUCHSTABE A DS-GVO ODER ART. 9 ABS. 2 BUCHSTABE A DS-GVO
                STÜTZTE, UND ES FEHLT AN EINER ANDERWEITIGEN RECHTSGRUNDLAGE FÜR
                DIE VERARBEITUNG DIE BETROFFENE PERSON LEGT GEMÄSS ART. 21 ABS.
                1 DS-GVO WIDERSPRUCH GEGEN DIE VERARBEITUNG EIN, UND ES LIEGEN
                KEINE VORRANGIGEN BERECHTIGTEN GRÜNDE FÜR DIE VERARBEITUNG VOR,
                ODER DIE BETROFFENE PERSON LEGT GEMÄSS ART. 21 ABS. 2 DS-GVO
                WIDERSPRUCH GEGEN DIE VERARBEITUNG EI DIE PERSONENBEZOGENEN
                DATEN WURDEN UNRECHTMÄSSIG VERARBEITET DIE LÖSCHUNG DER
                PERSONENBEZOGENEN DATEN IST ZUR ERFÜLLUNG EINER RECHTLICHEN
                VERPFLICHTUNG NACH DEM UNIONSRECHT ODER DEM RECHT DER
                MITGLIEDSTAATEN ERFORDERLICH, DEM DER VERANTWORTLICHE
                UNTERLIEGT. DIE PERSONENBEZOGENEN DATEN WURDEN IN BEZUG AUF
                ANGEBOTENE DIENSTE DER INFORMATIONSGESELLSCHAFT GEMÄSS ART. 8
                ABS. 1 DS-GVO ERHOBEN
              </Text>
            </section>
            <br />
            <Text variant="paragraph">
              SOFERN EINER DER OBEN GENANNTEN GRÜNDE ZUTRIFFT UND EINE
              BETROFFENE PERSON DIE LÖSCHUNG VON PERSONENBEZOGENEN DATEN, DIE
              BEI DER BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH GESPEICHERT SIND,
              VERANLASSEN MÖCHTE, KANN SIE SICH HIERZU JEDERZEIT AN EINEN
              MITARBEITER DES FÜR DIE VERARBEITUNG VERANTWORTLICHEN WENDEN. DER
              MITARBEITER DER BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH WIRD
              VERANLASSEN, DASS DEM LÖSCHVERLANGEN UNVERZÜGLICH NACHGEKOMMEN
              WIRD.
            </Text>
            <br />
            <Text variant="paragraph">
              WURDEN DIE PERSONENBEZOGENEN DATEN VON DER BOOTSHAUS WH
              BETRIEBSGESELLSCHAFT MBH ÖFFENTLICH GEMACHT UND IST UNSER
              UNTERNEHMEN ALS VERANTWORTLICHER GEMÄSS ART. 17 ABS. 1 DS-GVO ZUR
              LÖSCHUNG DER PERSONENBEZOGENEN DATEN VERPFLICHTET, SO TRIFFT DIE
              BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH UNTER BERÜCKSICHTIGUNG DER
              VERFÜGBAREN TECHNOLOGIE UND DER IMPLEMENTIERUNGSKOSTEN ANGEMESSENE
              MASSNAHMEN, AUCH TECHNISCHER ART, UM ANDERE FÜR DIE
              DATENVERARBEITUNG VERANTWORTLICHE, WELCHE DIE VERÖFFENTLICHTEN
              PERSONENBEZOGENEN DATEN VERARBEITEN, DARÜBER IN KENNTNIS ZU
              SETZEN, DASS DIE BETROFFENE PERSON VON DIESEN ANDEREN FÜR DIE
              DATENVERARBEITUNG VERANTWORTLICHEN DIE LÖSCHUNG SÄMTLICHER LINKS
              ZU DIESEN PERSONENBEZOGENEN DATEN ODER VON KOPIEN ODER
              REPLIKATIONEN DIESER PERSONENBEZOGENEN DATEN VERLANGT HAT, SOWEIT
              DIE VERARBEITUNG NICHT ERFORDERLICH IST. DER MITARBEITER DER
              BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH WIRD IM EINZELFALL DAS
              NOTWENDIGE VERANLASSEN.
            </Text>
            <br />
            <Text variant="heading">
              E) RECHT AUF EINSCHRÄNKUNG DER VERARBEITUNG
            </Text>
            <br />
            <Text variant="paragraph">
              JEDE VON DER VERARBEITUNG PERSONENBEZOGENER DATEN BETROFFENE
              PERSON HAT DAS VOM EUROPÄISCHEN RICHTLINIEN- UND VERORDNUNGSGEBER
              GEWÄHRTE RECHT, VON DEM VERANTWORTLICHEN DIE EINSCHRÄNKUNG DER
              VERARBEITUNG ZU VERLANGEN, WENN EINE DER FOLGENDEN VORAUSSETZUNGEN
              GEGEBEN IST:
            </Text>
            <br />
            <section className="ml-2">
              <Text variant="paragraph">
                DIE RICHTIGKEIT DER PERSONENBEZOGENEN DATEN WIRD VON DER
                BETROFFENEN PERSON BESTRITTEN, UND ZWAR FÜR EINE DAUER, DIE ES
                DEM VERANTWORTLICHEN ERMÖGLICHT, DIE RICHTIGKEIT DER
                PERSONENBEZOGENEN DATEN ZU ÜBERPRÜFEN. DIE VERARBEITUNG IST
                UNRECHTMÄSSIG, DIE BETROFFENE PERSON LEHNT DIE LÖSCHUNG DER
                PERSONENBEZOGENEN DATEN AB UND VERLANGT STATTDESSEN DIE
                EINSCHRÄNKUNG DER NUTZUNG DER PERSONENBEZOGENEN DATEN DER
                VERANTWORTLICHE BENÖTIGT DIE PERSONENBEZOGENEN DATEN FÜR DIE
                ZWECKE DER VERARBEITUNG NICHT LÄNGER, DIE BETROFFENE PERSON
                BENÖTIGT SIE JEDOCH ZUR GELTENDMACHUNG, AUSÜBUNG ODER
                VERTEIDIGUNG VON RECHTSANSPRÜCHEN. DIE BETROFFENE PERSON HAT
                WIDERSPRUCH GEGEN DIE VERARBEITUNG GEM. ART. 21 ABS. 1 DS-GVO
                EINGELEGT UND ES STEHT NOCH NICHT FEST, OB DIE BERECHTIGTEN
                GRÜNDE DES VERANTWORTLICHEN GEGENÜBER DENEN DER BETROFFENEN
                PERSON ÜBERWIEGEN.
              </Text>
            </section>
            <br />
            <Text variant="paragraph">
              SOFERN EINE DER OBEN GENANNTEN VORAUSSETZUNGEN GEGEBEN IST UND
              EINE BETROFFENE PERSON DIE EINSCHRÄNKUNG VON PERSONENBEZOGENEN
              DATEN, DIE BEI DER BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH
              GESPEICHERT SIND, VERLANGEN MÖCHTE, KANN SIE SICH HIERZU JEDERZEIT
              AN EINEN MITARBEITER DES FÜR DIE VERARBEITUNG VERANTWORTLICHEN
              WENDEN. DER MITARBEITER DER BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH
              WIRD DIE EINSCHRÄNKUNG DER VERARBEITUNG VERANLASSEN.
            </Text>
            <br />
            <Text variant="heading">F) RECHT AUF DATENÜBERTRAGBARKEIT</Text>
            <br />
            <Text variant="paragraph">
              Jede von der Verarbeitung personenbezogener Daten betroffene
              Person hat das vom Europäischen Richtlinien- und Verordnungsgeber
              gewährte Recht, die sie betreffenden personenbezogenen Daten,
              welche durch die betroffene Person einem Verantwortlichen
              bereitgestellt wurden, in einem strukturierten, gängigen und
              maschinenlesbaren Format zu erhalten. Sie hat außerdem das Recht,
              diese Daten einem anderen Verantwortlichen ohne Behinderung durch
              den Verantwortlichen, dem die personenbezogenen Daten
              bereitgestellt wurden, zu übermitteln, sofern die Verarbeitung auf
              der Einwilligung gemäß Art. 6 Abs. 1 Buchstabe a DS-GVO oder Art.
              9 Abs. 2 Buchstabe a DS-GVO oder auf einem Vertrag gemäß Art. 6
              Abs. 1 Buchstabe b DS-GVO beruht und die Verarbeitung mithilfe
              automatisierter Verfahren erfolgt, sofern die Verarbeitung nicht
              für die Wahrnehmung einer Aufgabe erforderlich ist, die im
              öffentlichen Interesse liegt oder in Ausübung öffentlicher Gewalt
              erfolgt, welche dem Verantwortlichen übertragen wurde.
            </Text>
            <br />
            <Text variant="paragraph">
              Ferner hat die betroffene Person bei der Ausübung ihres Rechts auf
              Datenübertragbarkeit gemäß Art. 20 Abs. 1 DS-GVO das Recht, zu
              erwirken, dass die personenbezogenen Daten direkt von einem
              Verantwortlichen an einen anderen Verantwortlichen übermittelt
              werden, soweit dies technisch machbar ist und sofern hiervon nicht
              die Rechte und Freiheiten anderer Personen beeinträchtigt werden.
            </Text>
            <br />
            <Text variant="paragraph">
              Ferner hat die betroffene Person bei der Ausübung ihres Rechts auf
              Datenübertragbarkeit gemäß Art. 20 Abs. 1 DS-GVO das Recht, zu
              erwirken, dass die personenbezogenen Daten direkt von einem
              Verantwortlichen an einen anderen Verantwortlichen übermittelt
              werden, soweit dies technisch machbar ist und sofern hiervon nicht
              die Rechte und Freiheiten anderer Personen beeinträchtigt werden.
            </Text>
            <br />
            <Text variant="paragraph">
              Zur Geltendmachung des Rechts auf Datenübertragbarkeit kann sich
              die betroffene Person jederzeit an einen Mitarbeiter der Bootshaus
              WH Betriebsgesellschaft mbH wenden.
            </Text>
            <br />
            <Text variant="heading">G) RECHT AUF WIDERSPRUCH</Text>
            <br />
            <Text variant="paragraph">
              JEDE VON DER VERARBEITUNG PERSONENBEZOGENER DATEN BETROFFENE
              PERSON HAT DAS VOM EUROPÄISCHEN RICHTLINIEN- UND VERORDNUNGSGEBER
              GEWÄHRTE RECHT, AUS GRÜNDEN, DIE SICH AUS IHRER BESONDEREN
              SITUATION ERGEBEN, JEDERZEIT GEGEN DIE VERARBEITUNG SIE
              BETREFFENDER PERSONENBEZOGENER DATEN, DIE AUFGRUND VON ART. 6 ABS.
              1 BUCHSTABEN E ODER F DS-GVO ERFOLGT, WIDERSPRUCH EINZULEGEN. DIES
              GILT AUCH FÜR EIN AUF DIESE BESTIMMUNGEN GESTÜTZTES PROFILING.
            </Text>
            <br />
            <Text variant="paragraph">
              DIE BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH VERARBEITET DIE
              PERSONENBEZOGENEN DATEN IM FALLE DES WIDERSPRUCHS NICHT MEHR, ES
              SEI DENN, WIR KÖNNEN ZWINGENDE SCHUTZWÜRDIGE GRÜNDE FÜR DIE
              VERARBEITUNG NACHWEISEN, DIE DEN INTERESSEN, RECHTEN UND
              FREIHEITEN DER BETROFFENEN PERSON ÜBERWIEGEN, ODER DIE
              VERARBEITUNG DIENT DER GELTENDMACHUNG, AUSÜBUNG ODER VERTEIDIGUNG
              VON RECHTSANSPRÜCHEN.
            </Text>
            <br />
            <Text variant="paragraph">
              VERARBEITET DIE BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH
              PERSONENBEZOGENE DATEN, UM DIREKTWERBUNG ZU BETREIBEN, SO HAT DIE
              BETROFFENE PERSON DAS RECHT, JEDERZEIT WIDERSPRUCH GEGEN DIE
              VERARBEITUNG DER PERSONENBEZOGENEN DATEN ZUM ZWECKE DERARTIGER
              WERBUNG EINZULEGEN. DIES GILT AUCH FÜR DAS PROFILING, SOWEIT ES
              MIT SOLCHER DIREKTWERBUNG IN VERBINDUNG STEHT. WIDERSPRICHT DIE
              BETROFFENE PERSON GEGENÜBER DER BOOTSHAUS WH BETRIEBSGESELLSCHAFT
              MBH DER VERARBEITUNG FÜR ZWECKE DER DIREKTWERBUNG, SO WIRD DIE
              BOOTSHAUS WH BETRIEBSGESELLSCHAFT MBH DIE PERSONENBEZOGENEN DATEN
              NICHT MEHR FÜR DIESE ZWECKE VERARBEITEN.
            </Text>
            <br />
            <Text variant="paragraph">
              ZUDEM HAT DIE BETROFFENE PERSON DAS RECHT, AUS GRÜNDEN, DIE SICH
              AUS IHRER BESONDEREN SITUATION ERGEBEN, GEGEN DIE SIE BETREFFENDE
              VERARBEITUNG PERSONENBEZOGENER DATEN, DIE BEI DER BOOTSHAUS WH
              BETRIEBSGESELLSCHAFT MBH ZU WISSENSCHAFTLICHEN ODER HISTORISCHEN
              FORSCHUNGSZWECKEN ODER ZU STATISTISCHEN ZWECKEN GEMÄSS ART. 89
              ABS. 1 DS-GVO ERFOLGEN, WIDERSPRUCH EINZULEGEN, ES SEI DENN, EINE
              SOLCHE VERARBEITUNG IST ZUR ERFÜLLUNG EINER IM ÖFFENTLICHEN
              INTERESSE LIEGENDEN AUFGABE ERFORDERLICH
            </Text>
            <br />
            <Text variant="paragraph">
              ZUR AUSÜBUNG DES RECHTS AUF WIDERSPRUCH KANN SICH DIE BETROFFENE
              PERSON DIREKT JEDEN MITARBEITER DER BOOTSHAUS WH
              BETRIEBSGESELLSCHAFT MBH ODER EINEN ANDEREN MITARBEITER WENDEN.
              DER BETROFFENEN PERSON STEHT ES FERNER FREI, IM ZUSAMMENHANG MIT
              DER NUTZUNG VON DIENSTEN DER INFORMATIONSGESELLSCHAFT, UNGEACHTET
              DER RICHTLINIE 2002/58/EG, IHR WIDERSPRUCHSRECHT MITTELS
              AUTOMATISIERTER VERFAHREN AUSZUÜBEN, BEI DENEN TECHNISCHE
              SPEZIFIKATIONEN VERWENDET WERDEN.
            </Text>
            <br />
            <Text variant="heading">
              h) Automatisierte Entscheidungen im Einzelfall einschließlich
              Profiling
            </Text>
            <br />
            <Text variant="paragraph">
              Jede von der Verarbeitung personenbezogener Daten betroffene
              Person hat das vom Europäischen Richtlinien- und Verordnungsgeber
              gewährte Recht, nicht einer ausschließlich auf einer
              automatisierten Verarbeitung — einschließlich Profiling —
              beruhenden Entscheidung unterworfen zu werden, die ihr gegenüber
              rechtliche Wirkung entfaltet oder sie in ähnlicher Weise erheblich
              beeinträchtigt, sofern die Entscheidung (1) nicht für den
              Abschluss oder die Erfüllung eines Vertrags zwischen der
              betroffenen Person und dem Verantwortlichen erforderlich ist, oder
              (2) aufgrund von Rechtsvorschriften der Union oder der
              Mitgliedstaaten, denen der Verantwortliche unterliegt, zulässig
              ist und diese Rechtsvorschriften angemessene Maßnahmen zur Wahrung
              der Rechte und Freiheiten sowie der berechtigten Interessen der
              betroffenen Person enthalten oder (3) mit ausdrücklicher
              Einwilligung der betroffenen Person erfolgt.
            </Text>
            <br />
            <Text variant="paragraph">
              Ist die Entscheidung (1) für den Abschluss oder die Erfüllung
              eines Vertrags zwischen der betroffenen Person und dem
              Verantwortlichen erforderlich oder (2) erfolgt sie mit
              ausdrücklicher Einwilligung der betroffenen Person, trifft die
              Bootshaus WH Betriebsgesellschaft mbH angemessene Maßnahmen, um
              die Rechte und Freiheiten sowie die berechtigten Interessen der
              betroffenen Person zu wahren, wozu mindestens das Recht auf
              Erwirkung des Eingreifens einer Person seitens des
              Verantwortlichen, auf Darlegung des eigenen Standpunkts und auf
              Anfechtung der Entscheidung gehört.
            </Text>
            <br />
            <Text variant="paragraph">
              Möchte die betroffene Person Rechte mit Bezug auf automatisierte
              Entscheidungen geltend machen, kann sie sich hierzu jederzeit an
              einen Mitarbeiter des für die Verarbeitung Verantwortlichen
              wenden.
            </Text>
            <br />
            <Text variant="heading">
              i) Recht auf Widerruf einer datenschutzrechtlichen Einwilligung
            </Text>
            <br />
            <Text variant="paragraph">
              Jede von der Verarbeitung personenbezogener Daten betroffene
              Person hat das vom Europäischen Richtlinien- und Verordnungsgeber
              gewährte Recht, eine Einwilligung zur Verarbeitung
              personenbezogener Daten jederzeit zu widerrufen.
            </Text>
            <br />
            <Text variant="paragraph">
              Möchte die betroffene Person ihr Recht auf Widerruf einer
              Einwilligung geltend machen, kann sie sich hierzu jederzeit an
              einen Mitarbeiter des für die Verarbeitung Verantwortlichen
              wenden.
            </Text>
          </section>
        </section>
        <br />
        <section>
          <Text variant="heading">
            7. Datenschutzbestimmungen zu Einsatz und Verwendung von Facebook
          </Text>
          <br />
          <Text variant="paragraph">
            Der für die Verarbeitung Verantwortliche hat auf dieser
            Internetseite Komponenten des Unternehmens Facebook integriert.
            Facebook ist ein soziales Netzwerk.
          </Text>
          <br />
          <Text variant="paragraph">
            Ein soziales Netzwerk ist ein im Internet betriebener sozialer
            Treffpunkt, eine Online-Gemeinschaft, die es den Nutzern in der
            Regel ermöglicht, untereinander zu kommunizieren und im virtuellen
            Raum zu interagieren. Ein soziales Netzwerk kann als Plattform zum
            Austausch von Meinungen und Erfahrungen dienen oder ermöglicht es
            der Internetgemeinschaft, persönliche oder unternehmensbezogene
            Informationen bereitzustellen. Facebook ermöglicht den Nutzern des
            sozialen Netzwerkes unter anderem die Erstellung von privaten
            Profilen, den Upload von Fotos und eine Vernetzung über
            Freundschaftsanfragen.
          </Text>
          <br />
          <Text variant="paragraph">
            Betreibergesellschaft von Facebook ist die Facebook, Inc., 1 Hacker
            Way, Menlo Park, CA 94025, USA. Für die Verarbeitung
            personenbezogener Daten Verantwortlicher ist, wenn eine betroffene
            Person außerhalb der USA oder Kanada lebt, die Facebook Ireland
            Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland.
          </Text>
          <br />
          <Text variant="paragraph">
            Durch jeden Aufruf einer der Einzelseiten dieser Internetseite, die
            durch den für die Verarbeitung Verantwortlichen betrieben wird und
            auf welcher eine Facebook-Komponente (Facebook-Plug-In) integriert
            wurde, wird der Internetbrowser auf dem informationstechnologischen
            System der betroffenen Person automatisch durch die jeweilige
            Facebook-Komponente veranlasst, eine Darstellung der entsprechenden
            Facebook-Komponente von Facebook herunterzuladen. Eine
            Gesamtübersicht über alle Facebook-Plug-Ins kann unter
            https://developers.facebook.com/docs/plugins/?locale=de_DE abgerufen
            werden. Im Rahmen dieses technischen Verfahrens erhält Facebook
            Kenntnis darüber, welche konkrete Unterseite unserer Internetseite
            durch die betroffene Person besucht wird.
          </Text>
          <br />
          <Text variant="paragraph">
            Sofern die betroffene Person gleichzeitig bei Facebook eingeloggt
            ist, erkennt Facebook mit jedem Aufruf unserer Internetseite durch
            die betroffene Person und während der gesamten Dauer des jeweiligen
            Aufenthaltes auf unserer Internetseite, welche konkrete Unterseite
            unserer Internetseite die betroffene Person besucht. Diese
            Informationen werden durch die Facebook-Komponente gesammelt und
            durch Facebook dem jeweiligen Facebook-Account der betroffenen
            Person zugeordnet. Betätigt die betroffene Person einen der auf
            unserer Internetseite integrierten Facebook-Buttons, beispielsweise
            den „Gefällt mir“-Button, oder gibt die betroffene Person einen
            Kommentar ab, ordnet Facebook diese Information dem persönlichen
            Facebook-Benutzerkonto der betroffenen Person zu und speichert diese
            personenbezogenen Daten.
          </Text>
          <br />
          <Text variant="paragraph">
            Facebook erhält über die Facebook-Komponente immer dann eine
            Information darüber, dass die betroffene Person unsere Internetseite
            besucht hat, wenn die betroffene Person zum Zeitpunkt des Aufrufs
            unserer Internetseite gleichzeitig bei Facebook eingeloggt ist; dies
            findet unabhängig davon statt, ob die betroffene Person die
            Facebook-Komponente anklickt oder nicht. Ist eine derartige
            Übermittlung dieser Informationen an Facebook von der betroffenen
            Person nicht gewollt, kann diese die Übermittlung dadurch
            verhindern, dass sie sich vor einem Aufruf unserer Internetseite aus
            ihrem Facebook-Account ausloggt.
          </Text>
          <br />
          <Text variant="paragraph">
            Die von Facebook veröffentlichte Datenrichtlinie, die unter
            https://de-de.facebook.com/about/privacy/ abrufbar ist, gibt
            Aufschluss über die Erhebung, Verarbeitung und Nutzung
            personenbezogener Daten durch Facebook. Ferner wird dort erläutert,
            welche Einstellungsmöglichkeiten Facebook zum Schutz der
            Privatsphäre der betroffenen Person bietet. Zudem sind
            unterschiedliche Applikationen erhältlich, die es ermöglichen, eine
            Datenübermittlung an Facebook zu unterdrücken. Solche Applikationen
            können durch die betroffene Person genutzt werden, um eine
            Datenübermittlung an Facebook zu unterdrücken.
          </Text>
        </section>
        <br />
        <section>
          <Text variant="heading">8. Rechtsgrundlage der Verarbeitung</Text>
          <br />
          <Text variant="paragraph">
            Art. 6 I lit. a DS-GVO dient unserem Unternehmen als Rechtsgrundlage
            für Verarbeitungsvorgänge, bei denen wir eine Einwilligung für einen
            bestimmten Verarbeitungszweck einholen. Ist die Verarbeitung
            personenbezogener Daten zur Erfüllung eines Vertrags, dessen
            Vertragspartei die betroffene Person ist, erforderlich, wie dies
            beispielsweise bei Verarbeitungsvorgängen der Fall ist, die für eine
            Lieferung von Waren oder die Erbringung einer sonstigen Leistung
            oder Gegenleistung notwendig sind, so beruht die Verarbeitung auf
            Art. 6 I lit. b DS-GVO. Gleiches gilt für solche
            Verarbeitungsvorgänge die zur Durchführung vorvertraglicher
            Maßnahmen erforderlich sind, etwa in Fällen von Anfragen zur unseren
            Produkten oder Leistungen. Unterliegt unser Unternehmen einer
            rechtlichen Verpflichtung durch welche eine Verarbeitung von
            personenbezogenen Daten erforderlich wird, wie beispielsweise zur
            Erfüllung steuerlicher Pflichten, so basiert die Verarbeitung auf
            Art. 6 I lit. c DS-GVO. In seltenen Fällen könnte die Verarbeitung
            von personenbezogenen Daten erforderlich werden, um lebenswichtige
            Interessen der betroffenen Person oder einer anderen natürlichen
            Person zu schützen. Dies wäre beispielsweise der Fall, wenn ein
            Besucher in unserem Betrieb verletzt werden würde und daraufhin sein
            Name, sein Alter, seine Krankenkassendaten oder sonstige
            lebenswichtige Informationen an einen Arzt, ein Krankenhaus oder
            sonstige Dritte weitergegeben werden müssten. Dann würde die
            Verarbeitung auf Art. 6 I lit. d DS-GVO beruhen. Letztlich könnten
            Verarbeitungsvorgänge auf Art. 6 I lit. f DS-GVO beruhen. Auf dieser
            Rechtsgrundlage basieren Verarbeitungsvorgänge, die von keiner der
            vorgenannten Rechtsgrundlagen erfasst werden, wenn die Verarbeitung
            zur Wahrung eines berechtigten Interesses unseres Unternehmens oder
            eines Dritten erforderlich ist, sofern die Interessen, Grundrechte
            und Grundfreiheiten des Betroffenen nicht überwiegen. Solche
            Verarbeitungsvorgänge sind uns insbesondere deshalb gestattet, weil
            sie durch den Europäischen Gesetzgeber besonders erwähnt wurden. Er
            vertrat insoweit die Auffassung, dass ein berechtigtes Interesse
            anzunehmen sein könnte, wenn die betroffene Person ein Kunde des
            Verantwortlichen ist (Erwägungsgrund 47 Satz 2 DS-GVO).
          </Text>
        </section>
        <br />
        <section>
          <Text variant="heading">
            9. Berechtigte Interessen an der Verarbeitung, die von dem
            Verantwortlichen oder einem Dritten verfolgt werden
          </Text>
          <br />
          <Text variant="paragraph">
            Basiert die Verarbeitung personenbezogener Daten auf Artikel 6 I
            lit. f DS-GVO ist unser berechtigtes Interesse die Durchführung
            unserer Geschäftstätigkeit zugunsten des Wohlergehens all unserer
            Mitarbeiter und unserer Anteilseigner.
          </Text>
        </section>
        <br />
        <section>
          <Text variant="heading">
            10. Dauer, für die die personenbezogenen Daten gespeichert werden
          </Text>
          <br />
          <Text variant="paragraph">
            Das Kriterium für die Dauer der Speicherung von personenbezogenen
            Daten ist die jeweilige gesetzliche Aufbewahrungsfrist. Nach Ablauf
            der Frist werden die entsprechenden Daten routinemäßig gelöscht,
            sofern sie nicht mehr zur Vertragserfüllung oder Vertragsanbahnung
            erforderlich sind.
          </Text>
        </section>
        <br />
        <section>
          <Text variant="heading">
            11. Gesetzliche oder vertragliche Vorschriften zur Bereitstellung
            der personenbezogenen Daten; Erforderlichkeit für den
            Vertragsabschluss; Verpflichtung der betroffenen Person, die
            personenbezogenen Daten bereitzustellen; mögliche Folgen der
            Nichtbereitstellung
          </Text>
          <br />
          <Text variant="paragraph">
            Wir klären Sie darüber auf, dass die Bereitstellung
            personenbezogener Daten zum Teil gesetzlich vorgeschrieben ist (z.B.
            Steuervorschriften) oder sich auch aus vertraglichen Regelungen
            (z.B. Angaben zum Vertragspartner) ergeben kann. Mitunter kann es zu
            einem Vertragsschluss erforderlich sein, dass eine betroffene Person
            uns personenbezogene Daten zur Verfügung stellt, die in der Folge
            durch uns verarbeitet werden müssen. Die betroffene Person ist
            beispielsweise verpflichtet uns personenbezogene Daten
            bereitzustellen, wenn unser Unternehmen mit ihr einen Vertrag
            abschließt. Eine Nichtbereitstellung der personenbezogenen Daten
            hätte zur Folge, dass der Vertrag mit dem Betroffenen nicht
            geschlossen werden könnte. Vor einer Bereitstellung
            personenbezogener Daten durch den Betroffenen muss sich der
            Betroffene an einen unserer Mitarbeiter wenden. Unser Mitarbeiter
            klärt den Betroffenen einzelfallbezogen darüber auf, ob die
            Bereitstellung der personenbezogenen Daten gesetzlich oder
            vertraglich vorgeschrieben oder für den Vertragsabschluss
            erforderlich ist, ob eine Verpflichtung besteht, die
            personenbezogenen Daten bereitzustellen, und welche Folgen die
            Nichtbereitstellung der personenbezogenen Daten hätte.
          </Text>
        </section>
        <br />
        <section>
          <Text variant="heading">
            12. Bestehen einer automatisierten Entscheidungsfindung
          </Text>
          <br />
          <Text variant="paragraph">
            Als verantwortungsbewusstes Unternehmen verzichten wir auf eine
            automatische Entscheidungsfindung oder ein Profiling.
          </Text>
          <br />
          <Text variant="paragraph">
            Diese Datenschutzerklärung wurde durch den
            Datenschutzerklärungs-Generator der DGD Deutsche Gesellschaft für
            Datenschutz GmbH, die als
          </Text>
          <Link to="https://dg-datenschutz.de/datenschutz-dienstleistungen/externer-datenschutzbeauftragter/">
            <Text variant="paragraph">
              Externer Datenschutzbeauftragter München
            </Text>
          </Link>
          <Text variant="paragraph">tätig ist, in Kooperation mit dem</Text>
          <Link to="https://www.wbs-law.de/it-recht/datenschutzrecht/">
            <Text variant="paragraph">
              Kölner IT- und Datenschutz Anwalt Christian Solmecke
            </Text>
          </Link>
        </section>
      </section>
    </section>
  );
};

export default Impressum;
